name: Build

on:
  push:
    branches:
      - main
      - ci-debug
      - release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      # --- fzf, rg, bat ---
      - run: src/test/install_deps.sh
        if: runner.os == 'Linux' || runner.os == 'macOS'

      # --- deps ---
      - run: npm install

      # --- build / test ---
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - run: npm test
        if: runner.os != 'Linux'

      # --- package ---
      - run: npm run vscode:package
        if: runner.os == 'Linux'

      - uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: find-it-faster-vsix
          path: "*.vsix"

      # --- publish! ---
      - if: github.ref == 'refs/heads/release' && runner.os == 'Linux'
        name: Publish!
        env:
          VSCE_PAT: ${{ secrets.FIND_IT_FASTER_AZURE_PAT }}
        run: |
          sudo apt-get install -y jq
          FIF_TAG=$(cat package.json | jq -r .version)
          npm run vscode:publish
          echo "Tagging release with $FIF_TAG..."
          git tag "$FIF_TAG"
          git push origin "$FIF_TAG"

  # publish:
  #   if: github.ref == 'refs/heads/ci-debug'
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10.x

  #     - name: Get vsix
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: find-it-faster-vsix

  #     - run: echo hello world

  #     - run: ls -lah

  #     - run: |
  #         npm install
  #         npm run compile
  #         echo done
  #         git status

  #     - run: |
  #         npm run vscode:publish
  #         git tag 
  #       env:
  #         VCSE_PAT: ${{ secrets.FIND_IT_FASTER_AZURE_PAT }}
