name: Build

on:
  push:
    branches:
      - main
      - ci-debug
      - release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    # --- fzf, rg, bat ---
    - run: src/test/install_deps.sh
      if: runner.os == 'Linux' || runner.os == 'macOS'

    # --- deps ---
    - run: npm install

    # --- build ---
    - run: npm run vscode:package

    # --- test ---
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'

    - run: npm test
      if: runner.os != 'Linux'
